name: Tinybird Push
description: Push changes to Tinybird data project
author: Alejandro Martin <hi@alejandromav.com>

inputs:
  token:
    description: Tinybird admin token
    required: true

  host:
    description: Tinybird region for your account
    required: false
    default: https://api.tinybird.co

  force:
    description: Flag to update existing objects or not
    required: false
    default: true

  populate:
    description: Populate materialized views with existing data
    required: false
    default: false

runs:
  using: docker
  image: Dockerfile
  env:
    TOKEN: ${{ inputs.token }}
    HOST: ${{ inputs.host }}
  args:
    - ${{ inputs.force}}

# For Github Marketplace listing
branding:
  icon: 'upload'  
  color: 'white'
